# Basic config
title: Expect Music and Riots
exclude: ["README.md", "LICENSE.md"]
theme: minima
permalink: pretty

# My info
author: Matt Duszynski
github_username: dzunk
description: "Sometimes science is more art than science."
